chore: start on autotools

diff --git a/auto b/auto
--- a/auto
+++ b/auto
@@ -1,10 +1,94 @@
 #!/bin/bash --
-set -axeuo pipefail
+set -aeo pipefail
 
-export COMMIT_SHA=$(git rev-parse --short HEAD)
-export RELEASE=$(rpm --eval "%autorelease -p -e pre1 -s ${COMMIT_SHA}")
+bail() {
+  cat <<-HELP
+Usage:
+  ./$(basename "${0}") <clean|gen|build>
 
-[[ "${1}" == "clean" ]] && . ./scripts/autoclean.sh && exit 0
-[[ "${1}" == "gen" ]] && . ./scripts/autogen.sh && exit 0
-[[ "${1}" == "tag" ]] && . ./scripts/autotag.sh && exit 0
-[[ "${1}" == "build" ]] && make dist-gzip && exit 0
+Smol utility script to help with using this repo
+
+HELP
+  exit 1
+}
+
+[[ -z "${1}" ]] && bail
+
+[[ -N "$DEBUG" ]] && set -x
+
+set -u
+
+# set some vars...
+PACKAGE="${NAME:-$(basename "$(pwd)")}"
+COMMIT_SHA=$(git rev-parse --short HEAD)
+RELEASE=$(rpm --eval "%autorelease -p -e pre1 -s ${COMMIT_SHA}")
+M4_LIBS="$(realpath .)/.m4"
+__delay=0.1
+
+# these have to be exported for use elsewhere
+export COMMIT_SHA RELEASE
+
+# util functions below
+
+good() {
+  echo "done!" && exit 0
+}
+
+# clean up any files created by this script
+# TODO: this could probably be handled with automake
+autoclean() {
+  echo "Removing files I (autoconf/automake) made" &&
+    sleep "$__delay" &&
+    echo "..." &&
+    sleep "$__delay" &&
+    \ # might as well run the makefile's distclean while it's here
+  (test ! -f Makefile || make distclean) &&
+    \ # generated by aclocal
+  rm -rf aclocal.m4 autom4te.cache &&
+    \ # generated by autoconf
+  rm -f configure configure\~ &&
+    \ # generated/installed by automake
+  rm -f Makefile.in &&
+    rm -rf .m4 &&
+    rm -f config.{log,status,guess} install-sh "${PACKAGE}.spec" missing Makefile &&
+    \ # build output
+  rm -rf ./*.tar.* &&
+    good
+}
+
+# setup script, runs autotools
+autogen() {
+  echo "setting up" &&
+    sleep "$__delay" &&
+    echo "..." &&
+    sleep "$__delay" &&
+    autoreconf -i -m || (
+
+    test -d "$M4_LIBS" || mkdir "$M4_LIBS"
+    test -f "${M4_LIBS}/aclocal.m4" || aclocal -I "$M4_LIBS" --output "${M4_LIBS}/aclocal.m4"
+    test -f configure || autoconf -I "$M4_LIBS" -DVERSION="$VERSION" -DPACKAGE_URL="$PACKAGE_URL" -DRELEASE="$RELEASE"
+    test -f Makefile || automake --add-missing --copy
+
+  ) &&
+    ./configure &&
+    good
+}
+
+# handle args
+case "${1}" in
+clean)
+  autoclean
+  ;;
+
+gen)
+  autogen
+  ;;
+
+build)
+  make dist-gzip && good
+  ;;
+
+*)
+  bail
+  ;;
+esac
